title: Article
preset: page
pages: false

fields:
  cover: 
    label: Cover Image
    type: files
  # category:
  #   label: Categories
  #   type: checkboxes
  #   options: query
  #   query: site.tags.toStructure
  #   width: 1/2
  text:
    label: Text
    type: textarea
    size: medium
  related: 
    label: Related pages
    type: pages
    query: page.siblings(false)

