title: Article
preset: page
pages: false

fields:
  cover: 
    label: Cover Image
    type: files
  text:
    label: Text
    type: textarea
    size: medium
  related: 
    label: Related pages
    type: pages
    query: page.siblings(false)

