title: Site
# preset: pages
# unlisted: true

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            headline: Pages
  settings:
    label: Parameters
    icon: settings
    columns:
      - width: 1/3
        sections:
          images:
            type: files
            template: image
            info: "{{ file.dimensions }}"
            size: small
      - width: 1/2
        fields:
          logo: 
            label: Website logo
            type: structure
            fields: 
              first: 
                label: First part
                type: text
              sign:
                label: Sign
                type: text
                help: you can choose a sign here https://unilist.raphaelbastide.com/#shapes
              second: 
                label: Second part
                type: text
          subtitle:
            label: Subtitle
            type: text
          sitecolor: 
            label: Website main color
            type: color
          author: 
            label: Author(s)
            type: text
          keywords:
            label: Tags (for search engines)
            type: tags
          description: 
            label: Description (for search engines)
            type: textarea
            size: small
          copyright: 
            label: Copyright
            type: text
  version: 
    label: versionning
    icon: clock
    columns: 
      - width: 1/2
        sections: 
          revisions:
            type: gitLog
            label: History
            limit: 5
            kirbyOnly: true  
      - width: 1/2
        sections: 
          log:
            type: gitRevisions
            label: Revisions
            fields:
              - title
              - text
            limit: 5
            columns:
              - author
              - hash
              - message 




